<Project Sdk="Microsoft.NET.Sdk">
		
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>paradigm_ehb.CommandCenter.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Google.Protobuf" Version="3.33.2" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Grpc.Tools" Version="2.76.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<!-- Global Includes -->

	<!-- Include all the *.proto files, with config for Client -->
	<ItemGroup>
		<Protobuf Include="Protos\Greet\V1\greet.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Health\V1\health.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Journal\V1\journal.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Resources\V1\resources.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Resources\V2\resources.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Services\V1\services.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Services\V2\services.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\Services\V3\services.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
