<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>paradigm_ehb.CommandCenter.WinUI</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Components\NewFolder\**" />
	  <EmbeddedResource Remove="Components\NewFolder\**" />
	  <None Remove="Components\NewFolder\**" />
	  <Page Remove="Components\NewFolder\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="Components\Interface1.cs" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Components\Reusable\Home_ServerOverview.xaml" />
	  <None Remove="HomePage.xaml" />
	  <None Remove="ServerCreation.xaml" />
	  <None Remove="SettingsPage.xaml" />
	  <None Remove="srvMgnt\ServerMainPage.xaml" />
	  <None Remove="srvMgnt\Views\ProcessesPage.xaml" />
	  <None Remove="srvMgnt\Views\ServerModification.xaml" />
	  <None Remove="srvMgnt\Views\srvOverview.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7175" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
	</ItemGroup>

	<!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\paradigm-ehb.CommandCenter.Core\paradigm-ehb.CommandCenter.Core.csproj" />
	</ItemGroup>


	<!-- Import the CommandCenter Core Namespace & make it Globally available -->
	<ItemGroup>
	  <Using Include="paradigm_ehb.CommandCenter.Core" />
	</ItemGroup>
	<ItemGroup>
	  <Page Update="ServerCreation.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="HomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Components\Reusable\Home_ServerOverview.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="srvMgnt\ServerMainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <PRIResource Remove="Components\NewFolder\**" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Components\Extensions\" />
	</ItemGroup>
	<ItemGroup>
	  <Page Update="srvMgnt\Views\ProcessesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="srvMgnt\Views\ServerModification.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="srvMgnt\Views\srvOverview.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>
